name: Deploy Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'packages/web/**'
      - 'packages/api/**'
      - 'packages/client-gql/**'
      - 'packages/ui/**'
  workflow_dispatch:

jobs:
  check-avail:
    runs-on: ubuntu-latest
    outputs:
      retVal: ${{ steps.request.outputs.return }}
    
    steps:
      - name: Make Request
        id: request
        run: "echo \"::set-output name=return::$(curl https://dev.oasis.sh/gha/devAvail)\""
      
  deploy:
    needs: check-avail
    runs-on: ubuntu-latest

    if: needs.check-avail.output.retVal == "true"
    steps:
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Check out the repository to $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Install node dependencies
      - name: Install node dependencies
        run: |
          npm install pm2 -g

      # Prepare to deploy
      - name: Prepare for deploy
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_DEPLOY_CONFIG }}" > /home/runner/.ssh/config
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 0600 /home/runner/.ssh/id_rsa

      # Run the deployment
      - name: Run deployment
        run: |
          cd $GITHUB_WORKSPACE
          pm2 deploy ecosystem-staging.config.js staging update
