name: Test

on:
  push:
    branches:
      - '*'
    paths:
      - "packages/web/**"
      - "packages/api/**"
  pull_request:
    branches:
      - '*'
    paths:
      - "packages/web/**"
      - "packages/api/**"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      OASIS_API_REDIS_URL: "redis://localhost:6379"
      OASIS_API_SESSION_SECRET: "dhfvgydsfbgsyefvc"
      OASIS_API_PUBLIC_DOMAIN: "localhost:3000"
      OASIS_API_TRUST_PROXY: "false"
      OASIS_API_SRC_PATH: $GITHUB_WORKSPACE + "packages/api/src"
      NEXT_PUBLIC_BASE_URL: "localhost:3000"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 15.1
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
        
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - run: yarn install
      
      - name: Setup
        run: |
          cp packages/api/src/ormconfig.example.ts packages/api/src/ormconfig.ts
          yarn build
          
      
      - run: yarn test
